In [0]:
import tensorflow as tf

In [0]:
# checking the shapes of the tensor
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )


In [7]:
with tf.Session() as session:
  result = session.run(Scalar)
  print("Scalar 1 entry: \n %s \n" % result)
  result = session.run(Vector)
  print("Scalar 1 entry: \n %s \n" % result)
  result = session.run(Matrix)
  print("Scalar 1 entry: \n %s \n" % result)
  result = session.run(Tensor)
  print("Scalar 1 entry: \n %s \n" % result)

Scalar 1 entry: 
 [2] 

Scalar 1 entry: 
 [5 6 2] 

Scalar 1 entry: 
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Scalar 1 entry: 
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [9]:
M_1 = tf.constant([[1,2,3],[2,3,4],[3,4,5]]) 
M_2 = tf.constant([[1,2,3],[2,3,4],[3,4,5]])

first = tf.add(M_1, M_2)
second = M_1 + M_2

with tf.Session() as session:
  result = session.run(first)
  print(result)
  result = session.run(second)
  print(result)

[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]
